"""
Project Euler Problem 2.

=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""
t = int(raw_input().strip())
for a0 in xrange(t):
    n = long(raw_input().strip())
    a, b = 1, 2
    result = []
    total = 0
    while a < n:
        result.append(a)
        tmp = b
        b = a + b
        a = tmp
    for num in result:
        if num % 2 == 0:
            total += num
    print total
